// Generated by https://quicktype.io

export interface GamesResponse {
  success: boolean;
  message: string;
  items:   Item[];
  params:  Params;
}

export interface Item {
  id:           number;
  providerId:   string;
  code:         string;
  name:         string;
  description:  string;
  position:     number;
  rtp:          null;
  version:      string;
  Common:       string;
  variation:    number;
  new:          number;
  locked:       number;
  active:       number;
  regUserId:    number;
  regDate:      string;
  regDatetime:  string;
  regTimestamp: number;
}

export interface Params {
  info:    Info;
  applied: Applied;
  allowed: Allowed;
}

export interface Allowed {
  filtering: Filtering[];
  paging:    AllowedPaging;
  sorting:   Sorting[];
}

export interface Filtering {
  hasOption: boolean;
  hint:      string;
  key:       string;
  label:     string;
  options:   any[];
}

export interface AllowedPaging {
  defaultLimit: number;
  size:         number;
}

export interface Sorting {
  key:   string;
  label: string;
}

export interface Applied {
  filtering: Ing;
  paging:    AppliedPaging;
  sorting:   Ing;
}

export interface Ing {
  enable: boolean;
  value:  string;
}

export interface AppliedPaging {
  enable:   boolean;
  page:     number;
  pageRows: number;
}

export interface Info {
  pageIndex: number;
  pageRows:  number;
  totalRows: number;
  pages:     number;
}
